#!/bin/bash

THIS_SCRIPT_NAME=$(basename "$0")
FIRST_ARG="$1"
SECOND_ARG="$2"
THIRD_ARG="$3"

function printUsage {
    printf "Usage:\n"
    printf "\t$THIS_SCRIPT_NAME validate (or v) counter-method (or c) STRING_TO_VALIDATE\n"
    printf "\t$THIS_SCRIPT_NAME validate (or v) recursion-method (or r) STRING_TO_VALIDATE\n"
    printf "\t$THIS_SCRIPT_NAME validate (or v) shortest-method (or sh) STRING_TO_VALIDATE\n"
    printf "\t$THIS_SCRIPT_NAME validate (or v) stack-method (or st) STRING_TO_VALIDATE\n"
    printf "\t$THIS_SCRIPT_NAME validate (or v) stack-list-method (or stl) STRING_TO_VALIDATE\n"
    printf "\t$THIS_SCRIPT_NAME run-benchmark (or b)\n"
    printf "\t$THIS_SCRIPT_NAME run-unit-tests (or t)\n"
}

case "$FIRST_ARG" in
    "run-benchmark"|"b")
        bash "./app/cli/benchmarking-cli/run-benchmark"
        ;;
    "run-unit-tests"|"t")
        bash "./app/cli/unit-testing-cli/run-unit-tests"
        ;;
    "validate"|"v")
        bash "./app/cli/validate-cli/validate" "$SECOND_ARG" "$THIRD_ARG"
        ;;
    "")
        printf "$THIS_SCRIPT_NAME: no particular subcommand specified.\n"
        printUsage
        ;;
    *)
        printf "$THIS_SCRIPT_NAME: $FIRST_ARG: subcommand uknown.\n"
        printUsage
        ;;
esac