#!/bin/bash

source ./app/cli/print-usage

THIS_SCRIPT_NAME=$(basename "$0")
FIRST_ARG="$1"
SECOND_ARG="$2"
THIRD_ARG="$3"

if [[ "$#" == 0 ]] ; then
    printf "\n$THIS_SCRIPT_NAME: no particular subcommand specified.\n"
    printUsage
    exit 1
elif [[ "$#" > 3 ]] ; then
    printf "\n$THIS_SCRIPT_NAME: too many arguments provided.\n"
    printUsage
    exit 1
fi

case "$FIRST_ARG" in
    "run-benchmark"|"b")
        bash "./app/cli/benchmarking-cli/run-benchmark" "$SECOND_ARG"
        ;;
    "run-unit-tests"|"t")
        bash "./app/cli/unit-testing-cli/run-unit-tests" "$SECOND_ARG"
        ;;
    "validate"|"v")
        if [[ "$#" == 3 ]] ; then
            bash "./app/cli/validation-cli/validate" "$SECOND_ARG" "$THIRD_ARG"
        elif [[ "$#" == 2 ]] ; then
            bash "./app/cli/validation-cli/validate" "$SECOND_ARG"
        elif [[ "$#" == 1 ]] ; then
            printf "\n$THIS_SCRIPT_NAME: no string to validate provided.\n"
            printUsage
            exit 1
        fi
        ;;
    "")
        printf "\n$THIS_SCRIPT_NAME: no particular subcommand specified.\n"
        printUsage
        exit 1
        ;;
    *)
        printf "\n$THIS_SCRIPT_NAME: $FIRST_ARG: subcommand uknown.\n"
        printUsage
        exit 1
        ;;
esac