#!/bin/bash

FIRST_ARG="$1"
SECOND_ARG="$2"

case "$FIRST_ARG" in
    "counter-method"|"c")
        node --experimental-modules "../modules/validate/validate.mjs" "counter" "$SECOND_ARG"
        ;;
    "recursion-method"|"r")
        node --experimental-modules "../modules/validate/validate.mjs" "recursion" "$SECOND_ARG"
        ;;
    "shortest-method"|"sh")
        node --experimental-modules "../modules/validate/validate.mjs" "shortest" "$SECOND_ARG"
        ;;
    "stack-method"|"st")
        node --experimental-modules "../modules/validate/validate.mjs" "stack" "$SECOND_ARG"
        ;;
    "stack-list-method"|"stl")
        node --experimental-modules "../modules/validate/validate.mjs" "stack-list" "$SECOND_ARG"
        ;;
    *)
        node --experimental-modules "../modules/validate/validate.mjs" "stack-list" "$FIRST_ARG"
        ;;
esac