#!/bin/bash

THIS_SCRIPT_NAME=$(basename "$0")
ARG="$1"

if [ -f "$ARG" ] ; then
    node "./app/logic/unit-testing-module/non-testable/run-unit-tests.js" "$ARG"
elif [ "$ARG" == "" ] ; then
    node "./app/logic/unit-testing-module/non-testable/run-unit-tests.js"
elif [ -e "$ARG" ] ; then
    printf "\n$THIS_SCRIPT_NAME: $ARG: file of wrong type specified. You may use only regular files.\n"
    exit 1
else
    printf "\n$THIS_SCRIPT_NAME: $ARG: the specified file does not exist.\n"
    exit 1
fi