#!/bin/bash

ARG="$1"

if [ -f "$ARG" ] ; then
    node "./app/logic/unit-testing/non-testable/run-unit-tests.js" "$ARG"
elif [ "$ARG" == "" ] ; then
    node "./app/logic/unit-testing/non-testable/run-unit-tests.js"
elif [ -e "$ARG" ] ; then
    printf "\nFile of wrong type specified: $ARG. You may use only regular files.\n"
    exit 1
else
    printf "\nThe specified file does not exist: $ARG.\n"
    exit 1
fi